site_name: Documentção
repo_url: https://github.com/unb-mds/2024-1-Squad01

nav:
  - Home: index.md
  - Sprints:
      - Sprint 0: sprints/sprint0.md
      - Sprint 1: sprints/sprint1.md

  - Estudos:
      - Métodos Ágeis: estudos/metodos-ageis.md

      - MkDocs: estudos/documentacao.md
      
      - Bibliografia: estudos/bibliografia.md

theme: material