site_name: Documentação forUnB
repo_url: https://github.com/unb-mds/2024-1-forUnB

nav:

  - Home: index.md
  - Sprints:
      - Sprint 0: sprints/sprint0.md
      - Sprint 1: sprints/sprint1.md
      - Sprint 2: sprints/sprint2.md

  - Estudos:
      - Lean Inception: lean_inception/lean_inception.md
      - Métodos Ágeis: estudos/metodos-ageis.md
      - MkDocs: estudos/documentacao.md
      - Bibliografia: estudos/bibliografia.md
  
  - Visão do produto: visao_do_produto/visao_produto.md
  - Arquitetura:  arquitetura/arquitetura.md
      



theme: material
